services:
  - type: web
    name: blackone-downloader-backend
    env: node
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y python3-pip ffmpeg curl && \
      pip3 install yt-dlp && \
      npm install
    startCommand: node server.js

